AWSTemplateFormatVersion: '2010-09-09'
Description: slack notification by aws chatbot

Parameters:
  SlackWorkspaceId:
    Type: String
    Description: Slack workspace Id from AWS console.
  SlackChannelId:
    Description: Slack channel Id.
    Type: String
  MonthlyCostBudget:
    Description: Monthly cost budget
    Type: Number
  AlertThresholdPercentage:
    Description: The percentage of Alert threshold.
    Type: Number
    Default: 80

Resources:
  chatbot:
    Type: AWS::Chatbot::SlackChannelConfiguration
    Properties: 
      ConfigurationName: slack-notification
      IamRoleArn: !GetAtt chatbotIamRole.Arn
      SlackChannelId: !Ref SlackChannelId
      SlackWorkspaceId: !Ref SlackWorkspaceId
      LoggingLevel: INFO
      SnsTopicArns: 
        - !Ref CloudWatchAlarmForChatbotTopic
  chatbotIamRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "chatbot.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
  CloudWatchAlarmForChatbotTopic:
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: aws-budget-notification
  snsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties: 
      PolicyDocument: 
        Version: "2008-10-17"
        Statement:
        - Sid: AWSBudgetsSNSPublishingPermissions
          Effect: Allow
          Principal:
            Service: budgets.amazonaws.com
          Action: "SNS:Publish"
          Resource: !Ref CloudWatchAlarmForChatbotTopic
      Topics: 
      - !Ref CloudWatchAlarmForChatbotTopic
    DependsOn: CloudWatchAlarmForChatbotTopic
  myBudget:
    Type: AWS::Budgets::Budget
    Properties: 
      Budget:
        BudgetLimit:
          Amount: !Ref MonthlyCostBudget
          Unit: USD
        BudgetType: COST
        TimeUnit: MONTHLY
      NotificationsWithSubscribers: 
        - Notification: 
            ComparisonOperator: GREATER_THAN
            NotificationType: ACTUAL
            Threshold: !Ref AlertThresholdPercentage
            ThresholdType: PERCENTAGE
          Subscribers: 
          - Address: !Ref CloudWatchAlarmForChatbotTopic
            SubscriptionType: SNS