AWSTemplateFormatVersion: '2010-09-09'
Description: slack notification by aws chatbot

Parameters:
  SlackWorkspaceId:
    Type: String
    Description: Slack workspace Id from AWS console.
  SlackChannelId:
    Description: Slack channel Id.
    Type: String

Resources:
  chatbot:
    Type: AWS::Chatbot::SlackChannelConfiguration
    Properties: 
      ConfigurationName: slack-notification
      IamRoleArn: !GetAtt chatbotIamRole.Arn
      SlackChannelId: !Ref SlackChannelId
      SlackWorkspaceId: !Ref SlackWorkspaceId
      # SnsTopicArns: 
      #   - !Ref snsTopic
  chatbotIamRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "chatbot.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
  # snsTopic:
  #   Type: AWS::SNS::Topic
  #   Properties: 
  #     TopicName: aws-budget-notification
  # snsTopicPolicy:
  #   Type: AWS::SNS::TopicPolicy
  #   Properties: 
  #     PolicyDocument: |
  #       {
  #         "Version": "2008-10-17",
  #         "Id": "__default_policy_ID",
  #         "Statement": [
  #           {
  #             "Sid": "AWSBudgetsSNSPublishingPermissions",
  #             "Effect": "Allow",
  #             "Principal": {
  #               "Service": "budgets.amazonaws.com"
  #             },
  #             "Action": "SNS:Publish",
  #             "Resource": "arn:aws:sns:ap-northeast-1:370929926236:development-infra_cost_notification"
  #           },
  #           {
  #             "Sid": "__default_statement_ID",
  #             "Effect": "Allow",
  #             "Principal": {
  #               "AWS": "*"
  #             },
  #             "Action": [
  #               "SNS:GetTopicAttributes",
  #               "SNS:SetTopicAttributes",
  #               "SNS:AddPermission",
  #               "SNS:RemovePermission",
  #               "SNS:DeleteTopic",
  #               "SNS:Subscribe",
  #               "SNS:ListSubscriptionsByTopic",
  #               "SNS:Publish",
  #               "SNS:Receive"
  #             ],
  #             "Resource": "arn:aws:sns:ap-northeast-1:370929926236:development-infra_cost_notification",
  #             "Condition": {
  #               "StringEquals": {
  #                 "AWS:SourceOwner": "370929926236"
  #               }
  #             }
  #           }
  #         ]
  #       }
  #     Topics: 
  #       - !Ref snsTopic
